# Generated by Django 5.0.6 on 2024-05-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_name',
            new_name='username',
        ),
    ]
