# Generated by Django 5.0.6 on 2024-05-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_rating_review_rating_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating_us',
            new_name='rating',
        ),
    ]
