# Generated by Django 5.0.4 on 2024-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('ordered_item', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
